services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
    volumes:
      - /home/joel/config/plex/config:/config
      - /home/joel/config/plex/transcode:/transcode
      - /mnt/hdd01/movies:/movies
      - /mnt/hdd01/private:/private
      - /mnt/hdd01/tv:/tv
      - /mnt/hdd01/sport:/sport
    restart: always
